version: "3.8"
services:
  db:
    image: postgres:15
    container_name: notes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: notes-backend
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/notesdb?schema=public"
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: notes-frontend
    environment:
      VITE_API_BASE: "http://localhost:3000/api"
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db-data: